apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: test-pg
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword